### ISSUE TITLE
Token query timeouts

### ISSUE THREAD

**Issue by romix** [davits/DyeVim#2]
I often get errors of the form:
Token query timeout for buffer filename.cpp interval [a, b]

It may be related to the fact that my project is rather big and clang probably needs more time for tokenization, etc.

Any ideas how to solve this? May be it is possible to increase the timeout or something like this?

**Comment by davits** [comment]
Are you experiencing timeouts constantly or from time to time when server/pc is busy ?

I've been experiencing timeouts too lately. And I have a gut feeling that adding timeout will not solve this, I need to be investigate it further (hoping I'm wrong).

But anyway the timeout option needs to be added and it should have been done a long ago.

**Comment by davits** [comment]
@romix I just added new option for the timeout: g:dyevim_timeout.
The default value for timeout was/is 10 milliseconds. When I started working on this, I did some testing and in ideal conditions getting tokens for ~50-100 lines would take ~7ms, so I decided to put 10ms timeout as a default.
But in practice on overloaded machines we both encountered timeouts.

Could you please set timeout in your vimrc to 20 (which is twice as much as needed) and see how it is going.
If timeouts are gone I will change default value to 20, it is still in comfortable range, and beside it is a worst case scenario, in average queries will return in <10ms.

**Comment by romix** [comment]
> Are you experiencing timeouts constantly or from time to time when server/pc is busy ?

Actually, not. I simply edit a big project on my MacBook Pro and scroll the file

> Could you please set timeout in your vimrc to 20 (which is twice as much as needed) and see how it is going.

I tried with timeout set to 20. It seems to help. I still can see the error message if I scroll very quickly in a file with 2000 lines. If I set it to 30, I almost never see the error message.

**Comment by davits** [comment]
Thanks @romix.
Closing the issue for now.
