### ISSUE TITLE
Please help to find the correct settings

### ISSUE THREAD

**Issue by Claudius42** [davits/DyeVim#4]
I am looking for a solution to use YouCompleteMe + functional solution for 'GoTo'(Definition) + syntax highlighting of c++11. YouCompleteMe is working but I can only jump to declaration.
I used your dotfiles and therefor your plugins 'davits/YouCompleteMe' and 'davits/DyeVim' and followed your guideline.
In order to have a basic test I created a simple example using cmake tutorial. Please find attached example. These are the steps I executed to build the attached sample
a) extract the files to folder 'step2-0-basic'
b) $> mkdir build && cd build
c) $> cmake -DUSE_MYMATH=1 ..
d) $> make
e) $> mv compile_commands.json ..
f) $> cd .. && gvim tutorial.cxx
--> syntax highlighting is not working properly and using mapping from your dotfiles/vimrc 'gD', while cursor is on 'mysqrt'-function, will not go to definition but to declaration of corresponding function.

Do you see any error in my configuration?
Do you have any working sample you may share?

Kind regards, Claudius
[step2-0-basic.zip](https://github.com/davits/DyeVim/files/1268560/step2-0-basic.zip)

**Comment by davits** [comment]
Hi @Claudius42, sorry for the late answer.
I followed the steps, and after opening tutorial.cxx both YouCompleteMe and DyeVim worked fine.
Does the YCM work in your setup ? What do you mean by syntax highlighting is not working ? Can you provide a screenshot ?

About jumping to definition: It works only if the definition is in the current translation unit, which is not for your case. https://github.com/davits/YouCompleteMe#the-gotodefinition-subcommand

**Comment by Claudius42** [comment]
Hi @davits, thanks for your kind support!
I have created a complete new '.vim' folder using your [dotfiles](https://github.com/davits/dotfiles). After that I did the following:
- install [vundle](https://github.com/VundleVim/Vundle.vim)
- started gvim
- called 'PluginUpdate'
- entered directory '~/.vim/bundle/YouCompleteMe/'
- $> CXX=g++-4.9 CC=gcc-4.9 USE_SYSTEM_LIBCLANG=ON ./install.py --clang-completer
- extract the attached zip ('sample2-geometry.zip') to folder 'sample2-geometry'
- $> mkdir build && cd build
- $> cmake ..
- $> make
- $> mv compile_commands.json ..
- $> cd .. && gvim Rectangle.cpp

Basically it is also a simple example as the one before ('step2-0-basic.zip') but using more C++, e.g. classes.
However, the syntax highlighting is still **not** as expected (simply comparing to the screen shots on your [page](https://camo.githubusercontent.com/e2c65565afd6dfe525ff106072e04026360c3521/687474703a2f2f692e696d6775722e636f6d2f4153516e4853302e706e673f31))!

I can use the shortcut 'gD' from your example, using YCM to move to declarations of member variables. Therefore I think YCM is working.

Do you have any simple sample I could try including ycm_extra_conf.py etc.?
Would you please share your file 'ycm_extra_conf.py'?
![screenshot - rectangle cpp](https://user-images.githubusercontent.com/18005387/30565318-0e3c900e-9cc8-11e7-80d4-f23590c1a8c4.png)

[sample2-geometry.zip](https://github.com/davits/DyeVim/files/1312199/sample2-geometry.zip)

Many thanks in advance!

**Comment by davits** [comment]
Please join to the room https://gitter.im/DyeVim/master .
I would like for you to run some commands on your setup, and it is a more appropriate place for such discussion.

**Comment by davits** [comment]
Fixed by 525a4a325a9167a09bba4207ad5461b264841644
