### ISSUE TITLE
Configuration with YCM+DyeVim running with gvim does not work in Neovim

### ISSUE THREAD

**Issue by Claudius42** [davits/DyeVim#6]
I use gvim and already configured an environment for programming in embedded software development in C. One of my favourite plugins is YCM and DyeVim. Currently I experiment with Neovim. I use the same .vimrc for gvim (v8.0.x) and neovim (0.2.2), OS is Xubuntu Xcfe 17.10. In gvim everything works fine. But when I start Neovim I receive the following error messages:

error durig execution of "function youcompleteme#Enable[13]..<SNR>150_SetUpBalloon".
row   1:
E518: unknown option: balloonexp=youcompleteme#BalloonEval()
row   2:
E518: unknown option: balloondelay=1000

I already figured out that vim must be compiled with the option "balloon_eval".

Is there an option to disable the Balloon features?

Yesterday I already entered this issue at https://groups.google.com and already received the information that the balloon feature is not part of the official release anymore. Do you plan to sync your repo with the official version of YCM in the near future?

Please let me know if you need any further logs/outputs.

Best regards and thanks in advance,
Claudius

**Comment by davits** [comment]
Thanks for the feedback.
I've added checks for the balloon feature with commit https://github.com/davits/YouCompleteMe/commit/1f3aa449430bef2be8640ab3bae3ebde30989daa
Now it should work fine for you, please try and let me know.

Balloon is just a feature I've added only in my fork for myself. It shows type of entity under mouse cursor when you hover.
As for the plans of merging, it is too much work for me to handle right now.

Regards,
Davit.

**Comment by Claudius42** [comment]
Hi @davits, thank you for your fast fix. This fixed the problem regarding the error messages. However, the syntax highlighting as well as the YCM features, e.g. GoToImprecise, are still not working.
When I use GoToImprecise I get the error message 'unknown arguments for the function <SNR>150_CompleterCommand'
Do you have any idea what is going wrong?
I have written this comment also on [Gitter](https://gitter.im/DyeVim/master)

**Comment by davits** [comment]
The issue was resolved after discussion on Gitter
