### ISSUE TITLE
just does nothing

### ISSUE THREAD

**Issue by real-or-random** [davits/DyeVim#7]
Sorry, this is not a very informative bug report.
Dyevim just does nothng in C++ files.

I installed your YCM and it works perfectly with semantic features. There is no error message. `:echo g:loaded_dyevim` shows `1`. I use solarized8 but even when I switch to wombat256_mod, things like `std` are not highlighted.

Any hints how to debug this?

**Comment by davits** [comment]
Hi @real-or-random, sorry for the late answer.
Are you using vim, gvim or neovim ?
Colorscheme naming is important, currently only `solarized`(has terminal support) and `wombat256mod`(no terminal support) are supported, but there is no support for `solarize8` or `wombat256_mod`(maybe there is a typo?).
Please try using gvim with `solarized` colorscheme and see if it works.
If it doesn't, uncomment this line and send me the generated log file (dyevim.log): https://github.com/davits/DyeVim/blob/cf3d86c556c6ab0d80de6c58d3589a7982e7467e/python/dye/dyevim.py#L44
